"""empty message

Revision ID: 01a4427599da
Revises: 
Create Date: 2017-11-07 08:54:34.850505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01a4427599da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verwijderd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nummer', sa.Integer(), nullable=True),
    sa.Column('Merk', sa.String(length=15), nullable=True),
    sa.Column('FrameType', sa.String(length=15), nullable=True),
    sa.Column('Kleur', sa.String(length=15), nullable=True),
    sa.Column('Framenummer', sa.String(length=50), nullable=True),
    sa.Column('Gegraveerde_postcode', sa.String(length=30), nullable=True),
    sa.Column('Opmerkingen', sa.String(length=200), nullable=True),
    sa.Column('Datum_aangemeld', sa.Date(), nullable=True),
    sa.Column('Datum_aangepast', sa.Date(), nullable=True),
    sa.Column('Datum_verwijderd', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Framenummer'),
    sa.UniqueConstraint('Framenummer'),
    sa.UniqueConstraint('Nummer'),
    sa.UniqueConstraint('Nummer')
    )
    op.drop_constraint('fiets_ibfk_2', 'fiets', type_='foreignkey')
    op.drop_column('fiets', 'aangepast_door')
    op.drop_column('fiets', 'Datum_verwijderd')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiets', sa.Column('Datum_verwijderd', sa.DATE(), nullable=True))
    op.add_column('fiets', sa.Column('aangepast_door', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('fiets_ibfk_2', 'fiets', 'user', ['aangepast_door'], ['id'])
    op.drop_table('verwijderd')
    ### end Alembic commands ###
