"""empty message

Revision ID: 22e3ea07330c
Revises: de873a9728ad
Create Date: 2017-10-27 09:53:49.282388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22e3ea07330c'
down_revision = 'de873a9728ad'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fiets_ibfk_2', 'fiets', type_='foreignkey')
    op.drop_column('fiets', 'aangepast_door')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiets', sa.Column('aangepast_door', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('fiets_ibfk_2', 'fiets', 'user', ['aangepast_door'], ['id'])
    ### end Alembic commands ###
