"""empty message

Revision ID: 28bccba952a9
Revises: 69ef9425edae
Create Date: 2017-10-09 07:26:17.394290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28bccba952a9'
down_revision = '69ef9425edae'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiets', sa.Column('Datum_aangepast', sa.Date(), nullable=True))
    op.add_column('fiets', sa.Column('Datum_verwijderd', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiets', 'Datum_verwijderd')
    op.drop_column('fiets', 'Datum_aangepast')
    ### end Alembic commands ###
