"""empty message

Revision ID: 69ef9425edae
Revises: 
Create Date: 2017-10-09 07:14:58.498691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ef9425edae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiets',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Nummer', sa.Integer(), nullable=True),
    sa.Column('Merk', sa.String(length=15), nullable=True),
    sa.Column('FrameType', sa.String(length=15), nullable=True),
    sa.Column('Kleur', sa.String(length=15), nullable=True),
    sa.Column('Framenummer', sa.String(length=50), nullable=True),
    sa.Column('Gegraveerde_postcode', sa.String(length=30), nullable=True),
    sa.Column('Opmerkingen', sa.String(length=200), nullable=True),
    sa.Column('Datum', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Framenummer'),
    sa.UniqueConstraint('Framenummer'),
    sa.UniqueConstraint('Nummer'),
    sa.UniqueConstraint('Nummer')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('authenticated', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('fiets')
    ### end Alembic commands ###
