"""empty message

Revision ID: 85a4a2bfd35e
Revises: 66f5cfb3b9ff
Create Date: 2017-10-11 08:01:11.829968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a4a2bfd35e'
down_revision = '66f5cfb3b9ff'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiets', sa.Column('Foto', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiets', 'Foto')
    ### end Alembic commands ###
