"""empty message

Revision ID: 9ae87c609504
Revises: f872cf9b1658
Create Date: 2017-10-17 10:32:19.343444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ae87c609504'
down_revision = 'f872cf9b1658'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fiets_ibfk_2', 'fiets', type_='foreignkey')
    op.drop_column('fiets', 'user_edt')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiets', sa.Column('user_edt', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('fiets_ibfk_2', 'fiets', 'user', ['user_edt'], ['id'])
    ### end Alembic commands ###
