"""empty message

Revision ID: de873a9728ad
Revises: 9ae87c609504
Create Date: 2017-10-27 09:28:12.290448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de873a9728ad'
down_revision = '9ae87c609504'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiets', sa.Column('aangepast_door', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fiets', 'user', ['aangepast_door'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fiets', type_='foreignkey')
    op.drop_column('fiets', 'aangepast_door')
    ### end Alembic commands ###
